/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 free_car_001.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/free_car_001.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.car_body.geometry} material={materials.MAIN}>
        <mesh geometry={nodes.door_l.geometry} material={materials.MAIN} position={[0.914, 0.683, 0.638]}>
          <mesh geometry={nodes.win_door_l001.geometry} material={materials.WINDOW} position={[-0.155, 0.696, -0.735]} />
        </mesh>
        <mesh geometry={nodes.door_r.geometry} material={materials.MAIN} position={[-0.914, 0.683, 0.638]}>
          <mesh geometry={nodes.win_door_r001.geometry} material={materials.WINDOW} position={[0.155, 0.696, -0.735]} />
        </mesh>
        <mesh geometry={nodes.free_number.geometry} material={materials.MAIN} position={[0, 0.793, -1.768]} />
        <mesh geometry={nodes.interior.geometry} material={materials.MAIN} position={[0.941, 0.6, -0.074]} rotation={[0, 0, -Math.PI / 2]} scale={[0.445, 0.398, 0.398]} />
        <mesh geometry={nodes.wheel_bl.geometry} material={materials.MAIN} position={[0.782, 0.325, -1.241]} rotation={[0, 1.571, 0]} scale={0.325} />
        <mesh geometry={nodes.wheel_br.geometry} material={materials.MAIN} position={[-0.782, 0.325, -1.241]} rotation={[0, 1.571, 0]} scale={0.325} />
        <mesh geometry={nodes.wheel_fl.geometry} material={materials.MAIN} position={[0.782, 0.325, 1.071]} rotation={[0, 1.571, 0]} scale={0.325} />
        <mesh geometry={nodes.wheel_fr.geometry} material={materials.MAIN} position={[-0.782, 0.325, 1.071]} rotation={[0, 1.571, 0]} scale={0.325} />
        <mesh geometry={nodes.windows.geometry} material={materials.WINDOW} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/free_car_001.gltf')
