/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 logo_test_1.gltf --transform 
Files: logo_test_1.gltf [14.33KB] > /home/john/projects/fxrebate/frontend3/public/logo_test_1-transformed.glb [132.44KB] (-824%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo_test_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shape002.geometry} material={materials.PaletteMaterial001} position={[-0.374, 0, 0.088]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/logo_test_1-transformed.glb')
