import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "@/components/layout/Layout";
import "./globals.css";
import "aos/dist/aos.css";
import "bootstrap/dist/css/bootstrap.min.css"
import 'swiper/css';
import "swiper/css/navigation";
import "swiper/css/pagination";


//import "@/assets/css/plugins/aos.css"
import "@/../public/assets/css/plugins/fontawesome.css"
import "@/../public/assets/css/plugins/slick-slider.css"
import "@/../public/assets/css/plugins/nice-select.css"
import "@/../public/assets/css/plugins/fonts.css"
import "@/../public/assets/css/master.css"
import "@/../public/assets/css/h4-master.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FXrEBATE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Layout headerStyle={1} footerStyle={1}>
    
        {children}
         
      </Layout>
      </body>
    
    </html>
  );
}
